package com.guisehn.main;

import java.util.Arrays;

public class Individual {
    
    private final MagicSquareFitnessCalculator fitnessCalculator;
    private final int[] square;
    private final int[] parent1;
    private final int[] parent2;
    private final boolean mutated;
    private final String crossoverDetails;
    private Integer fitness;
    private int age;
    
    public Individual(int[] square, int[] parent1, int[] parent2,
            boolean mutated, String crossoverDetails,
            MagicSquareFitnessCalculator fitnessCalculator) {
        this.square = square;
        this.parent1 = parent1;
        this.parent2 = parent2;
        this.mutated = mutated;
        this.crossoverDetails = crossoverDetails;
        this.fitnessCalculator = fitnessCalculator;
        this.age = 0;
    }

    public int[] getSquare() {
        return square;
    }

    public int[] getParent1() {
        return parent1;
    }

    public int[] getParent2() {
        return parent2;
    }

    public boolean isMutated() {
        return mutated;
    }
    
    public int getAge() {
        return age;
    }
    
    public int increaseAge() {
        return ++age;
    }

    public String getCrossoverDetails() {
        return crossoverDetails;
    }

    public int getFitness() {
        if (fitness == null) {
            fitness = fitnessCalculator.calculateFitness(square, true);
        }

        return fitness;
    }
    
    public String toString(boolean includeFitness) {
        return Arrays.toString(square) +
            (includeFitness ? " - Fitness: " + getFitness() : "");
    }

    @Override
    public String toString() {
        return toString(false);
    }
    
    @Override
    public boolean equals(Object object) {
        if (object instanceof Individual) {
            return object.toString().equals(this.toString());
        }
        
        return false;
    }

    // Generated by NetBeans
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + Arrays.hashCode(this.square);
        return hash;
    }
    
}
